env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Rust Tests

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  # This job should be run on presubmit, if any continuous-only tests are added we will need to input test-type above
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout pending changes
        uses: protocolbuffers/protobuf-ci/checkout@v3
        with:
          ref: ${{ inputs.safe-checkout }}
      - name: Run tests
        uses: protocolbuffers/protobuf-ci/bazel-docker@v3
        with:
          image: "us-docker.pkg.dev/protobuf-build/containers/common/linux/bazel:7.1.1-97f82260fd504923d8af642d567afb2d83a1959d"
          credentials: ${{ steps.esc-secrets.outputs.GAR_SERVICE_ACCOUNT }}
          bazel-cache: rust_linux
          bazel: >-
            test //rust:protobuf_upb_test //rust:protobuf_cpp_test
            //rust/test/rust_proto_library_unit_test:rust_upb_aspect_test
            //src/google/protobuf/compiler/rust/...
